sudo: required
services: 
  - docker

before_install: 
  - docker build -t jawdenwebb/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true jawdenwebb/react-test npm test -- ----coverage

after_success: 
  - docker build -t jawdenwebb/multi-client ./client
  - docker build -t jawdenwebb/multi-nginx ./nginx
  - docker build -t jawdenwebb/multi-server ./server
  - docker build -t jawdenwebb/multi-worker ./worker
#login with docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#push to docker hub
  - docker push jawdenwebb/multi-client
  - docker push jawdenwebb/multi-nginx 
  - docker push jawdenwebb/multi-server
  - docker push jawdenwebb/multi-worker